# permissions for end users to view podspecs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podspec-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: podspec-operator
    app.kubernetes.io/part-of: podspec-operator
    app.kubernetes.io/managed-by: kustomize
  name: podspec-viewer-role
rules:
- apiGroups:
  - example.example.com
  resources:
  - podspecs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.example.com
  resources:
  - podspecs/status
  verbs:
  - get
